server:
  port: 8068
  contextPath: /dockerMgrApi/
  consoleCode: true # 控制台验证码开关

db:
  driverName: mysql # 可选：mysql、sqlite3
  dataSourceUrl: root:cc123456@tcp(175.178.115.60:3306)/docker?charset=utf8
  useCache: false # 是否启用缓存，sqlite下，缓存会容易导致数据库文件锁定